Metrics/LineLength:
  Max: 174

Style/Documentation:
  Enabled: false

SignalException:
  # prefer raise to fail
  EnforcedStyle: only_raise

Lint/HandleExceptions:
  Exclude:
    - 'lib/sorted/active_record.rb'
